=== DanKristiansen/indexingplatform/schema/denormalization/denormalized-ddi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:d="http://dda.dk/ddi/denormalized-ddi" targetNamespace="http://dda.dk/ddi/denormalized-ddi" elementFormDefault="qualified">
  
    <xs:element name="DenormalizedDdi" type="d:DenormalizedDdiType" />
    
    <xs:complexType name="DenormalizedDdiType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="VariableList" type="d:VariableListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="QuestionItemList" type="d:QuestionItemListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="MultipleQuestionItemList" type="d:MultipleQuestionItemListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="UniverseList" type="d:UniverseListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="ConceptList" type="d:ConceptListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="CategoryList" type="d:CategoryListType" minOccurs="0" maxOccurs="1" />
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="VariableListType">
        <xs:sequence>
            <xs:element name="Variable" type="d:DdiElementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="QuestionItemListType">
        <xs:sequence>
            <xs:element name="QuestionItem" type="d:DdiElementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="MultipleQuestionItemListType">
        <xs:sequence>
            <xs:element name="MultipleQuestionItem" type="d:DdiElementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="UniverseListType">
        <xs:sequence>
            <xs:element name="Universe" type="d:DdiElementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ConceptListType">
        <xs:sequence>
            <xs:element name="Concept" type="d:DdiElementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="CategoryListType">
        <xs:sequence>
            <xs:element name="Category" type="d:DdiElementType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="DdiElementType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="VariableReferenceList" type="d:VariableReferenceListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="QuestionItemReferenceList" type="d:QuestionItemeReferenceListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="MultipleQuestionItemReferenceList" type="d:MultipleQuestionItemReferenceListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="UniverseReferenceList" type="d:UniverseReferenceListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="ConceptReferenceList" type="d:ConceptReferenceListType" minOccurs="0" maxOccurs="1" />
            <xs:element name="CategoryReferenceList" type="d:CategoryReferenceListType" minOccurs="0" maxOccurs="1" />
        </xs:choice>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="studyId" type="xs:string" use="required" />
    </xs:complexType>
    
    <xs:complexType name="VariableReferenceListType">
        <xs:sequence>
            <xs:element name="VariableReference" type="d:ReferenceType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="QuestionItemeReferenceListType">
        <xs:sequence>
            <xs:element name="QuestionItemReference" type="d:ReferenceType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="MultipleQuestionItemReferenceListType">
        <xs:sequence>
            <xs:element name="MultipleQuestionItemReference" type="d:ReferenceType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="UniverseReferenceListType">
        <xs:sequence>
            <xs:element name="UniverseReference" type="d:ReferenceType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ConceptReferenceListType">
        <xs:sequence>
            <xs:element name="ConceptReference" type="d:ReferenceType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="CategoryReferenceListType">
        <xs:sequence>
            <xs:element name="CategoryReference" type="d:ReferenceType" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ReferenceType">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
    
</xs:schema>

=== DanKristiansen/indexingplatform/xml-sample-instances/dernormalization0.xml
<?xml version="1.0" encoding="UTF-8"?>
<DenormalizedDdi xmlns="http://dda.dk/ddi/denormalized-ddi"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://dda.dk/ddi/denormalized-ddi file:/C:/Users/kp/Dropbox/DDA/DDA-IPF/schema/denormalization/denormalized-ddi.xsd">
    <ConceptList>
        <Concept id="id1" studyId="studyId1">
            <ConceptReference id="id3"/>
            <ConceptReference id="id5"/>
            <VariableReference id="id7"/>
        </Concept>
        <Concept id="id9" studyId="studyId3">
            <VariableReference id="id11"/>
            <MultipleQuestionItemReference id="id13"/>
            <VariableReference id="id15"/>
        </Concept>
        <Concept id="id17" studyId="studyId5">
            <UniverseReference id="id19"/>
            <UniverseReference id="id21"/>
            <CategoryReference id="id23"/>
        </Concept>
    </ConceptList>
    <QuestionItemList>
        <QuestionItem id="id25" studyId="studyId7">
            <VariableReference id="id27"/>
            <MultipleQuestionItemReference id="id29"/>
            <QuestionItemReference id="id31"/>
        </QuestionItem>
        <QuestionItem id="id33" studyId="studyId9">
            <QuestionItemReference id="id35"/>
            <MultipleQuestionItemReference id="id37"/>
            <CategoryReference id="id39"/>
        </QuestionItem>
        <QuestionItem id="id41" studyId="studyId11">
            <MultipleQuestionItemReference id="id43"/>
            <ConceptReference id="id45"/>
            <MultipleQuestionItemReference id="id47"/>
        </QuestionItem>
    </QuestionItemList>
    <ConceptList>
        <Concept id="id49" studyId="studyId13">
            <MultipleQuestionItemReference id="id51"/>
            <MultipleQuestionItemReference id="id53"/>
            <ConceptReference id="id55"/>
        </Concept>
        <Concept id="id57" studyId="studyId15">
            <QuestionItemReference id="id59"/>
            <MultipleQuestionItemReference id="id61"/>
            <ConceptReference id="id63"/>
        </Concept>
        <Concept id="id65" studyId="studyId17">
            <UniverseReference id="id67"/>
            <ConceptReference id="id69"/>
            <ConceptReference id="id71"/>
        </Concept>
    </ConceptList>
</DenormalizedDdi>
